### ISSUE TITLE
Support ST3

### ISSUE THREAD

**Issue by ghost** [relikd/Plist-Binary_sublime#2]
Hotkey or panel command doesn't do anything.

**Comment by relikd** [comment]
actually I can't test until I bought ST3 … which I'm waiting till it's released. Furthermore the porting guide doesn't tell me anything to change: http://www.sublimetext.com/docs/3/porting_guide.html

If you're familiar with programming plugins you can try to fix it, otherwise wait till it's got released, please.

**Comment by ghost** [comment]
It took me a while to research (no Python/ST API knowledge at all) but the [fix](https://github.com/relikd/Plist-Binary_sublime/pull/3) was easy peasy.

**Comment by relikd** [comment]
well done, thanks for the effort

**Comment by wamatt** [comment]
So does it work with ST3?

For comparison here is another pluging  https://github.com/tyrone-sudeium/st3-binaryplist I'm guessing it does something similar?

**Comment by relikd** [comment]
yes it does work with ST3 but the plugin you linked looks even better. I will update my description to advertise it ;-)
